/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/authContext`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin` | `/admin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/saved` | `/saved`; params?: Router.UnknownInputParams; } | { pathname: `/middleware/DetailsPage`; params?: Router.UnknownInputParams; } | { pathname: `/middleware/EditProfile`; params?: Router.UnknownInputParams; } | { pathname: `/middleware/Filter`; params?: Router.UnknownInputParams; } | { pathname: `/middleware/PropertyCard`; params?: Router.UnknownInputParams; } | { pathname: `/property/AddProperty`; params?: Router.UnknownInputParams; } | { pathname: `/property/EditProperty`; params?: Router.UnknownInputParams; } | { pathname: `/property/PropertyList`; params?: Router.UnknownInputParams; } | { pathname: `/screens/login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/register`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/authContext`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/admin` | `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/saved` | `/saved`; params?: Router.UnknownOutputParams; } | { pathname: `/middleware/DetailsPage`; params?: Router.UnknownOutputParams; } | { pathname: `/middleware/EditProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/middleware/Filter`; params?: Router.UnknownOutputParams; } | { pathname: `/middleware/PropertyCard`; params?: Router.UnknownOutputParams; } | { pathname: `/property/AddProperty`; params?: Router.UnknownOutputParams; } | { pathname: `/property/EditProperty`; params?: Router.UnknownOutputParams; } | { pathname: `/property/PropertyList`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/login`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/register`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/authContext${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/admin${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/saved${`?${string}` | `#${string}` | ''}` | `/saved${`?${string}` | `#${string}` | ''}` | `/middleware/DetailsPage${`?${string}` | `#${string}` | ''}` | `/middleware/EditProfile${`?${string}` | `#${string}` | ''}` | `/middleware/Filter${`?${string}` | `#${string}` | ''}` | `/middleware/PropertyCard${`?${string}` | `#${string}` | ''}` | `/property/AddProperty${`?${string}` | `#${string}` | ''}` | `/property/EditProperty${`?${string}` | `#${string}` | ''}` | `/property/PropertyList${`?${string}` | `#${string}` | ''}` | `/screens/login${`?${string}` | `#${string}` | ''}` | `/screens/register${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/authContext`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin` | `/admin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/saved` | `/saved`; params?: Router.UnknownInputParams; } | { pathname: `/middleware/DetailsPage`; params?: Router.UnknownInputParams; } | { pathname: `/middleware/EditProfile`; params?: Router.UnknownInputParams; } | { pathname: `/middleware/Filter`; params?: Router.UnknownInputParams; } | { pathname: `/middleware/PropertyCard`; params?: Router.UnknownInputParams; } | { pathname: `/property/AddProperty`; params?: Router.UnknownInputParams; } | { pathname: `/property/EditProperty`; params?: Router.UnknownInputParams; } | { pathname: `/property/PropertyList`; params?: Router.UnknownInputParams; } | { pathname: `/screens/login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/register`; params?: Router.UnknownInputParams; };
    }
  }
}
